//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.09.25 at 10:57:27 PM CEST 
//


package bank;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bank package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bank
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BalanceRequest }
     * 
     */
    public BalanceRequest createBalanceRequest() {
        return new BalanceRequest();
    }

    /**
     * Create an instance of {@link BalanceResponse }
     * 
     */
    public BalanceResponse createBalanceResponse() {
        return new BalanceResponse();
    }

    /**
     * Create an instance of {@link WithdrawResponse }
     * 
     */
    public WithdrawResponse createWithdrawResponse() {
        return new WithdrawResponse();
    }

    /**
     * Create an instance of {@link WithdrawRequest }
     * 
     */
    public WithdrawRequest createWithdrawRequest() {
        return new WithdrawRequest();
    }

    /**
     * Create an instance of {@link DepositRequest }
     * 
     */
    public DepositRequest createDepositRequest() {
        return new DepositRequest();
    }

    /**
     * Create an instance of {@link CustomerDetailsResponse }
     * 
     */
    public CustomerDetailsResponse createCustomerDetailsResponse() {
        return new CustomerDetailsResponse();
    }

    /**
     * Create an instance of {@link Customer }
     * 
     */
    public Customer createCustomer() {
        return new Customer();
    }

    /**
     * Create an instance of {@link DepositResponse }
     * 
     */
    public DepositResponse createDepositResponse() {
        return new DepositResponse();
    }

    /**
     * Create an instance of {@link CustomerDetailsRequest }
     * 
     */
    public CustomerDetailsRequest createCustomerDetailsRequest() {
        return new CustomerDetailsRequest();
    }

    /**
     * Create an instance of {@link Account }
     * 
     */
    public Account createAccount() {
        return new Account();
    }

}
